allowBuilds:
  '@parcel/watcher': true
  core-js-pure: true
  esbuild: true
minimumReleaseAgeExclude:
  - '@tanstack/form-core@1.32.1'
  - '@tanstack/form-devtools@0.2.28'
  - '@tanstack/react-form-devtools@0.2.28'
  - '@tanstack/react-form@1.32.1'
  - '@tanstack/react-start-client@1.168.5'
  - '@tanstack/react-start@1.168.14'
  - nodemailer@8.0.9
  - '@better-auth/core@1.6.14'
  - '@better-auth/drizzle-adapter@1.6.14'
  - '@better-auth/kysely-adapter@1.6.14'
  - '@better-auth/memory-adapter@1.6.14'
  - '@better-auth/mongo-adapter@1.6.14'
  - '@better-auth/prisma-adapter@1.6.14'
  - '@better-auth/telemetry@1.6.14'
  - '@tanstack/query-core@5.101.0'
  - '@tanstack/query-devtools@5.101.0'
  - '@tanstack/react-query-devtools@5.101.0'
  - '@tanstack/react-query@5.101.0'
  - '@tanstack/react-router@1.170.11'
  - '@tanstack/react-start-client@1.168.8'
  - '@tanstack/react-start-rsc@0.1.18'
  - '@tanstack/react-start-server@1.167.14'
  - '@tanstack/react-start@1.168.19'
  - '@tanstack/router-core@1.171.9'
  - '@tanstack/router-generator@1.167.13'
  - '@tanstack/router-plugin@1.168.14'
  - '@tanstack/start-client-core@1.170.7'
  - '@tanstack/start-plugin-core@1.171.11'
  - '@tanstack/start-server-core@1.169.9'
  - '@tanstack/start-storage-context@1.167.11'
  - better-auth@1.6.14
  - '@better-auth/core@1.6.16'
  - '@better-auth/drizzle-adapter@1.6.16'
  - '@better-auth/kysely-adapter@1.6.16'
  - '@better-auth/memory-adapter@1.6.16'
  - '@better-auth/mongo-adapter@1.6.16'
  - '@better-auth/prisma-adapter@1.6.16'
  - '@better-auth/telemetry@1.6.16'
  - '@better-fetch/fetch@1.2.2'
  - baseline-browser-mapping@2.10.35
  - better-auth@1.6.16
  - better-call@1.3.6
  - '@base-ui/react@1.6.0'
  - '@base-ui/utils@0.3.1'
  - '@dotenvx/dotenvx@1.74.2'
  - effect@3.21.4
  - '@tanstack/react-router@1.170.17'
  - '@tanstack/react-start-client@1.168.15'
  - '@tanstack/react-start-rsc@0.1.26'
  - '@tanstack/react-start-server@1.167.21'
  - '@tanstack/react-start@1.168.27'
  - '@tanstack/router-core@1.171.14'
  - '@tanstack/router-generator@1.167.18'
  - '@tanstack/router-plugin@1.168.19'
  - '@tanstack/start-client-core@1.170.13'
  - '@tanstack/start-plugin-core@1.171.19'
  - '@tanstack/start-server-core@1.169.16'
  - '@tanstack/start-storage-context@1.167.16'
  - baseline-browser-mapping@2.10.41
  - vite@8.1.3
onlyBuiltDependencies:
  - '@parcel/watcher'
  - core-js-pure
  - esbuild
